
  cmd_vel_timeout: 50
  allow_multiple_cmd_vel_publishers: false
  wheel_separation_h: 1.0
  wheel_radius: 2.0

    ## System limits x vel and acc
  linear/x/has_velocity_limits: true
  linear/x/has_acceleration_limits: true
  linear/x/max_velocity: 5.0
  linear/x/min_velocity: 0.0
  linear/x/max_acceleration: 8.0
  linear/x/min_acceleration: 0.0

  ## System Limits angular
  angular/z/has_velocity_limits: true
  angular/z/has_acceleration_limits: true
  angular/z/max_velocity: 1.0
  angular/z/min_velocity: 0.0
  angular/z/max_acceleration: 8.0
  angular/z/min_acceleration: 0.0
